global:
  scrape_interval: 4s
  external_labels:
    monitor: 'prometheus-monitor'
  query_log_file: 'prometheus-query-log.log'


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["16.170.226.129:5000"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
  - job_name: pushgateway
    honor_labels: false
    static_configs:
    - targets: ['localhost:9091']
      labels:
        pushgateway_instance: metricfire