apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myingress
spec:
  tls:
    - hosts:
        - myapp.com
      secretName: secret-name
  rules:
    - host: myapp.com
      http:
        paths:
          pathType: Prefix
          path: /
          backend:
            service:
              name:
              port:
                number:
