version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    depends_on:
      - api
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "3000:3000"
