apiVersion: apps/v1
kind: Deployment
metadata:
# Additional Info about the deployment is the annotation
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"learning"},"name":"nginx-deployment","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"learning"}},"template":{"metadata":{"labels":{"app":"learning"}},"spec":{"containers":[{"image":"nginx:1.16","name":"nginx","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2023-03-08T15:08:18Z"
  generation: 1
  labels:
    app: learning
  name: nginx-deployment
  namespace: default
  resourceVersion: "3611"
  uid: fa531044-3942-40b4-8bf7-3fafb87af79b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: learning
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: learning
    spec:
      containers:
        - image: nginx:1.16
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2023-03-08T15:08:20Z"
      lastUpdateTime: "2023-03-08T15:08:20Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-03-08T15:08:18Z"
      lastUpdateTime: "2023-03-08T15:08:20Z"
      message: ReplicaSet "nginx-deployment-74bd6959b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
