version: "3"
services:
  node-app:
    container_name: nodejs_app
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      - app=nodejs_app
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
