version: "3"
services:
  node-app:
    container_name: node-app@latest
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - app=my-node-app
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

networks:
  node-network:
    driver: bridge
